download-dependencies:
	wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.25/swagger-codegen-cli-3.0.25.jar -O swagger-codegen-cli.jar

generate: download-dependencies
	java -jar C:\Users\BRREG\swagger-codegen-cli.jar generate -i C:\Users\BRREG\Documents\GitHub\roterepo\csharpExperiment\swagger_yr.yml -l csharp -o C:\Users\BRREG\Documents\GitHub\roterepo\csharpExperiment\swagger