swagger: "2.0"
info:
  description: "Testing yr"
  title: "test"
  version: "1.0"
  
  
host: "api.met.no"
basePath: "/weatherapi/locationforecast/2.0"

schemes: 
 - "https"

paths:
  /status:
    get:
      responses:
        "200":
          description: "Success"
      
      operationId: GetStatus
        
      tags:
        - "weather"
      
      produces: 
      - "application/json"
      
  /compact:
    get:
      responses:
        "200":
          description: "Success" 
        
      parameters:
        - name: "altitude"
          in: "query"
          type: "integer"
          default: 0
          
        - name: "lat"
          in: "query"
          type: "string"
       
        - name: "lon"
          in: "query"
          type: "string"   

      produces: 
      - "application/json"